"""master_sequence_indel.py

Inference for a shared "master" symbol sequence under an insertion/deletion model.

Problem setting
---------------
You observe many sequences over a discrete alphabet (e.g., extracted from pairs of graphs).
Each observed sequence is assumed to arise from a single unknown master sequence via:
  1) Deletions of master elements (each master symbol is independently deleted w.p. p_del), and
  2) Insertions of background symbols (a geometric run of i.i.d. symbols from background
     distribution bg is inserted before each master symbol, and also at the end).

This file implements:
  - Background estimation (empirical + smoothing)
  - Likelihood of observed sequences given a master sequence (log-forward DP)
  - Optional Viterbi alignment
  - MCMC / simulated annealing search over master sequences (including variable length)
  - Simple grid search wrapper for (length, p_ins, p_del)

Dependencies: numpy (required). tqdm (optional).

Author: generated by ChatGPT
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple, Union

import math
import numpy as np

try:
    from tqdm.auto import tqdm  # type: ignore

    _HAVE_TQDM = True
except Exception:
    tqdm = None
    _HAVE_TQDM = False


TokenSeq = Union[str, Sequence[str], np.ndarray]


# -----------------------------
# Alphabet + encoding utilities
# -----------------------------


def _to_tokens(x: TokenSeq) -> List[str]:
    """Convert input to a list of tokens.

    - If x is a string, treat it as a sequence of characters.
    - If x is a sequence/array, coerce each element to str.
    """
    if isinstance(x, str):
        return list(x)
    if isinstance(x, np.ndarray):
        return [str(t) for t in x.tolist()]
    return [str(t) for t in x]


@dataclass(frozen=True)
class Alphabet:
    """A finite alphabet with encode/decode maps."""

    tokens: Tuple[str, ...]
    token_to_id: Dict[str, int]

    @staticmethod
    def from_sequences(seqs: Sequence[TokenSeq]) -> "Alphabet":
        uniq: Dict[str, None] = {}
        for s in seqs:
            for t in _to_tokens(s):
                uniq.setdefault(t, None)
        tokens = tuple(sorted(uniq.keys()))
        token_to_id = {t: i for i, t in enumerate(tokens)}
        return Alphabet(tokens=tokens, token_to_id=token_to_id)


    @staticmethod
    def from_tokens(tokens: Sequence[str]) -> "Alphabet":
        """Build an Alphabet from an explicit ordered token list.

        The token order defines the integer encoding. Duplicate tokens are not allowed.
        """
        toks = [str(t) for t in tokens]
        if len(set(toks)) != len(toks):
            raise ValueError("Duplicate tokens in alphabet.")
        tokens_t = tuple(toks)
        token_to_id = {t: i for i, t in enumerate(tokens_t)}
        return Alphabet(tokens=tokens_t, token_to_id=token_to_id)

    @property
    def size(self) -> int:
        return len(self.tokens)

    def encode(self, seq: TokenSeq) -> np.ndarray:
        toks = _to_tokens(seq)
        out = np.empty(len(toks), dtype=np.int32)
        for i, t in enumerate(toks):
            if t not in self.token_to_id:
                raise KeyError(f"Token {t!r} not in alphabet.")
            out[i] = self.token_to_id[t]
        return out

    def decode(self, arr: np.ndarray) -> List[str]:
        arr = np.asarray(arr, dtype=np.int64)
        return [self.tokens[int(i)] for i in arr]


# -----------------------------
# Background model
# -----------------------------


@dataclass
class BackgroundModel:
    """Categorical background distribution over an Alphabet."""

    alphabet: Alphabet
    probs: np.ndarray  # shape (A,)

    @staticmethod
    def fit(
        seqs: Sequence[TokenSeq],
        alphabet: Alphabet,
        pseudocount: float = 1e-2,
    ) -> "BackgroundModel":
        """Fit bg by empirical counts with additive smoothing."""
        counts = np.full(alphabet.size, float(pseudocount), dtype=np.float64)
        for s in seqs:
            enc = alphabet.encode(s)
            if enc.size:
                binc = np.bincount(enc, minlength=alphabet.size).astype(np.float64)
                counts += binc
        probs = counts / counts.sum()
        return BackgroundModel(alphabet=alphabet, probs=probs)

    def sample(self, rng: np.random.Generator, size: int = 1) -> np.ndarray:
        return rng.choice(self.alphabet.size, size=size, p=self.probs)


# -----------------------------
# Indel model + likelihood
# -----------------------------


@dataclass(frozen=True)
class IndelParams:
    """Parameters for the insertion/deletion model."""

    p_ins: float  # probability of inserting a background symbol before processing next master symbol
    p_del: float  # probability of deleting a master symbol when it is processed
    bg_probs: np.ndarray  # shape (A,)
    eps_sub: float = 0.0  # substitution/noise rate for master emissions

    def __post_init__(self):
        if not (0.0 <= self.p_ins < 1.0):
            raise ValueError("p_ins must be in [0,1).")
        if not (0.0 <= self.p_del < 1.0):
            raise ValueError("p_del must be in [0,1).")
        if not (0.0 <= self.eps_sub <= 1.0):
            raise ValueError("eps_sub must be in [0,1].")
        bg = np.asarray(self.bg_probs, dtype=np.float64)
        if bg.ndim != 1 or bg.size == 0:
            raise ValueError("bg_probs must be a non-empty 1D array.")
        if np.any(bg < 0) or not np.isfinite(bg).all():
            raise ValueError("bg_probs must be finite and nonnegative.")
        s = float(bg.sum())
        if not (s > 0):
            raise ValueError("bg_probs must sum to a positive value.")


@dataclass(frozen=True)
class IndelModelParams:
    """User-facing parameters that also carry the Alphabet.

    This is a thin wrapper around :class:`IndelParams` used internally.
    """

    alphabet: Alphabet
    p_ins: float
    p_del: float
    bg_probs: np.ndarray
    eps_sub: float = 0.0

    def __post_init__(self):
        bg = np.asarray(self.bg_probs, dtype=np.float64)
        if bg.ndim != 1 or bg.size != self.alphabet.size:
            raise ValueError("bg_probs must be a 1D array of length alphabet.size")

    def to_core(self) -> "IndelParams":
        return IndelParams(
            p_ins=float(self.p_ins),
            p_del=float(self.p_del),
            bg_probs=np.asarray(self.bg_probs, dtype=np.float64),
            eps_sub=float(self.eps_sub),
        )


def _log1m(p: float) -> float:
    """Stable log(1-p) for p in [0,1)."""
    # Clip to avoid log(0) due to floating error.
    if p >= 1.0:
        return -math.inf
    if p <= 0.0:
        return 0.0
    return math.log1p(-p)


def _logaddexp(a: float, b: float) -> float:
    return float(np.logaddexp(a, b))


class IndelLikelihood:
    """Likelihood and alignment routines under the indel model."""

    def __init__(self, params: IndelParams):
        self.params = params
        bg = np.asarray(params.bg_probs, dtype=np.float64)
        self.log_bg = np.log(bg / bg.sum())
        self.log_p_ins = math.log(params.p_ins) if params.p_ins > 0 else -math.inf
        self.log_1m_p_ins = _log1m(params.p_ins)
        self.log_p_del = math.log(params.p_del) if params.p_del > 0 else -math.inf
        self.log_1m_p_del = _log1m(params.p_del)

    def emission_logp(self, master_sym: int, obs_sym: int) -> float:
        """log P(obs_sym | master_sym) with optional noise."""
        eps = self.params.eps_sub
        if eps <= 0.0:
            return 0.0 if master_sym == obs_sym else -math.inf
        # P = (1-eps) * 1_{equal} + eps * bg(obs)
        base = eps * math.exp(self.log_bg[obs_sym])
        if master_sym == obs_sym:
            return math.log((1.0 - eps) + base)
        return math.log(base)

    def forward_loglik(self, master: np.ndarray, obs: np.ndarray) -> float:
        """Compute log P(obs | master, params) via forward DP (O(L*M), O(M) memory).

        master: int array of shape (L,)
        obs:    int array of shape (M,)
        """
        master = np.asarray(master, dtype=np.int32)
        obs = np.asarray(obs, dtype=np.int32)
        L = int(master.size)
        M = int(obs.size)

        # DP row for fixed i: log prob of generating obs[:j] after consuming i master symbols.
        row = np.full(M + 1, -math.inf, dtype=np.float64)
        row[0] = 0.0

        for i in range(L + 1):
            # Close insertions on this row: allow any number of inserts before processing next master symbol.
            if self.params.p_ins > 0.0 and M > 0:
                for j in range(M):
                    cur = float(row[j])
                    if not np.isfinite(cur):
                        continue
                    cand = cur + self.log_p_ins + float(self.log_bg[obs[j]])
                    row[j + 1] = np.logaddexp(row[j + 1], cand)

            if i == L:
                break

            next_row = np.full(M + 1, -math.inf, dtype=np.float64)
            ms = int(master[i])
            for j in range(M + 1):
                cur = float(row[j])
                if not np.isfinite(cur):
                    continue

                # Delete master symbol (no emission)
                if np.isfinite(self.log_p_del):
                    cand = cur + self.log_1m_p_ins + self.log_p_del
                    next_row[j] = np.logaddexp(next_row[j], cand)

                # Emit (match/substitute) master symbol
                if j < M and np.isfinite(self.log_1m_p_del):
                    elp = self.emission_logp(ms, int(obs[j]))
                    if np.isfinite(elp):
                        cand = cur + self.log_1m_p_ins + self.log_1m_p_del + elp
                        next_row[j + 1] = np.logaddexp(next_row[j + 1], cand)

            row = next_row

        # Stop after finishing the tail insertion-run
        return float(row[M]) + float(self.log_1m_p_ins)

    def viterbi_alignment(self, master: np.ndarray, obs: np.ndarray) -> Tuple[float, List[Tuple[str, Optional[int], Optional[int]]]]:
        """Most likely alignment path (Viterbi) with backpointers.

        Returns (log_prob, path) where path is a list of steps:
          ('I', None, j)  : inserted obs[j]
          ('D', i, None)  : deleted master[i]
          ('M', i, j)     : emitted obs[j] from master[i]

        Note: O(L*M) memory.
        """
        master = np.asarray(master, dtype=np.int32)
        obs = np.asarray(obs, dtype=np.int32)
        L = int(master.size)
        M = int(obs.size)

        dp = np.full((L + 1, M + 1), -math.inf, dtype=np.float64)
        bp: List[List[Optional[Tuple[int, int, str]]]] = [[None] * (M + 1) for _ in range(L + 1)]
        dp[0, 0] = 0.0

        for i in range(L + 1):
            for j in range(M + 1):
                cur = float(dp[i, j])
                if not np.isfinite(cur):
                    continue

                # Insert
                if j < M and np.isfinite(self.log_p_ins):
                    cand = cur + self.log_p_ins + float(self.log_bg[obs[j]])
                    if cand > dp[i, j + 1]:
                        dp[i, j + 1] = cand
                        bp[i][j + 1] = (i, j, 'I')

                # Process master if any left
                if i < L:
                    # Delete
                    if np.isfinite(self.log_p_del):
                        cand = cur + self.log_1m_p_ins + self.log_p_del
                        if cand > dp[i + 1, j]:
                            dp[i + 1, j] = cand
                            bp[i + 1][j] = (i, j, 'D')

                    # Emit
                    if j < M and np.isfinite(self.log_1m_p_del):
                        elp = self.emission_logp(int(master[i]), int(obs[j]))
                        if np.isfinite(elp):
                            cand = cur + self.log_1m_p_ins + self.log_1m_p_del + elp
                            if cand > dp[i + 1, j + 1]:
                                dp[i + 1, j + 1] = cand
                                bp[i + 1][j + 1] = (i, j, 'M')

        # Include stop prob
        best = float(dp[L, M]) + float(self.log_1m_p_ins)

        # Backtrack
        path: List[Tuple[str, Optional[int], Optional[int]]] = []
        i, j = L, M
        while not (i == 0 and j == 0):
            prev = bp[i][j]
            if prev is None:
                # No path (should be rare unless parameters make generation impossible)
                break
            pi, pj, step = prev
            if step == 'I':
                path.append(('I', None, pj))
            elif step == 'D':
                path.append(('D', pi, None))
            else:
                path.append(('M', pi, pj))
            i, j = pi, pj
        path.reverse()
        return best, path


# -----------------------------
# Master-sequence inference
# -----------------------------


@dataclass
class MCMCResult:
    best_master: np.ndarray
    best_score: float
    trace_best_scores: List[float]
    accept_rate: float


def _default_length_prior_logp(L: int, lam: float = 0.0) -> float:
    """A simple exponential length prior: log P(L) ∝ -lam * L."""
    return -lam * float(L)


class MasterSequenceEstimator:
    """Estimate master sequence (and optionally its length) under IndelLikelihood."""

    def __init__(
        self,
        alphabet: Alphabet,
        sequences: Sequence[TokenSeq],
        params: Union[IndelParams, IndelModelParams],
        length_prior_lambda: float = 0.0,
        seed: int = 0,
    ):
        self.alphabet = alphabet
        # Allow either IndelParams (core) or IndelModelParams (user-facing).
        if isinstance(params, IndelModelParams):
            params_core = params.to_core()
        else:
            params_core = params
        self.params = params_core
        self.lik = IndelLikelihood(params_core)
        self.rng = np.random.default_rng(seed)
        self.length_prior_lambda = float(length_prior_lambda)

        # Encode observations once.
        self.obs = [alphabet.encode(s) for s in sequences]

    def loglik_all(self, master: np.ndarray) -> float:
        master = np.asarray(master, dtype=np.int32)
        total = 0.0
        for o in self.obs:
            ll = self.lik.forward_loglik(master, o)
            if not np.isfinite(ll):
                return -math.inf
            total += ll
        return float(total)

    def logposterior(self, master: np.ndarray) -> float:
        master = np.asarray(master, dtype=np.int32)
        return self.loglik_all(master) + _default_length_prior_logp(int(master.size), self.length_prior_lambda)

    # ---- initializers ----

    def init_from_shortest(self) -> np.ndarray:
        """Initialize master as the shortest observed sequence (a crude but often decent start)."""
        idx = int(np.argmin([o.size for o in self.obs]))
        return np.array(self.obs[idx], copy=True)

    def init_random(self, length: int) -> np.ndarray:
        return self.rng.integers(0, self.alphabet.size, size=int(length), dtype=np.int32)

    # ---- MCMC proposals ----

    def _available_move_weights(self, fixed_length: bool) -> Dict[str, float]:
        w = {'sub': 1.0}
        if not fixed_length:
            w['ins'] = 0.5
            w['del'] = 0.5
        return w

    def propose(self, master: np.ndarray, fixed_length: bool = False) -> Tuple[np.ndarray, float]:
        """Propose a new master sequence.

        Returns (proposal, log_q_reverse_minus_log_q_forward).
        """
        master = np.asarray(master, dtype=np.int32)
        L = int(master.size)
        A = int(self.alphabet.size)

        weights = self._available_move_weights(fixed_length=fixed_length)
        keys = list(weights.keys())
        probs = np.array([weights[k] for k in keys], dtype=np.float64)
        probs = probs / probs.sum()

        move = str(self.rng.choice(keys, p=probs))

        def p_move_for(keys_here: List[str], move_name: str) -> float:
            # recompute normalized weights in a context
            w = np.array([weights[k] for k in keys_here], dtype=np.float64)
            w = w / w.sum()
            return float(w[keys_here.index(move_name)])

        if move == 'sub':
            if L == 0:
                # fallback to insertion if allowed
                if fixed_length:
                    return master.copy(), 0.0
                move = 'ins'
            else:
                pos = int(self.rng.integers(0, L))
                old = int(master[pos])
                new_sym = int(self.rng.integers(0, A - 1))
                if new_sym >= old:
                    new_sym += 1
                prop = master.copy()
                prop[pos] = new_sym
                # symmetric given pos chosen uniformly and new_sym chosen uniformly among A-1
                return prop, 0.0

        if move == 'ins':
            if fixed_length:
                return master.copy(), 0.0
            pos = int(self.rng.integers(0, L + 1))
            sym = int(self.rng.integers(0, A))
            prop = np.empty(L + 1, dtype=np.int32)
            prop[:pos] = master[:pos]
            prop[pos] = sym
            prop[pos + 1 :] = master[pos:]

            # Proposal ratio for reversible-jump insertion/deletion
            # q(forward) = P_ins(old) * 1/(L+1) * 1/A
            # q(reverse) = P_del(new) * 1/(L+1)
            keys_old = keys
            keys_new = keys
            p_ins_old = p_move_for(keys_old, 'ins')
            p_del_new = p_move_for(keys_new, 'del')
            log_ratio = math.log(p_del_new) - math.log(p_ins_old) + math.log(A)
            return prop, log_ratio

        if move == 'del':
            if fixed_length or L == 0:
                return master.copy(), 0.0
            pos = int(self.rng.integers(0, L))
            prop = np.concatenate([master[:pos], master[pos + 1 :]]).astype(np.int32, copy=False)

            # Reverse is insertion
            # q(forward) = P_del(old) * 1/L
            # q(reverse) = P_ins(new) * 1/L * 1/A
            keys_old = keys
            keys_new = keys
            p_del_old = p_move_for(keys_old, 'del')
            p_ins_new = p_move_for(keys_new, 'ins')
            log_ratio = math.log(p_ins_new) - math.log(p_del_old) - math.log(A)
            return prop, log_ratio

        return master.copy(), 0.0

    # ---- MCMC driver ----

    def run_mcmc(
        self,
        init_master: Optional[np.ndarray] = None,
        n_steps: int = 5000,
        burn_in: int = 500,
        thin: int = 10,
        fixed_length: bool = False,
        temperature: float = 1.0,
        progress: bool = True,
    ) -> MCMCResult:
        """Metropolis-Hastings (optionally annealed via temperature < 1).

        Returns the best master visited (maximum log posterior).
        """
        if init_master is None:
            cur = self.init_from_shortest()
        else:
            cur = np.asarray(init_master, dtype=np.int32).copy()

        cur_score = self.logposterior(cur)
        best = cur.copy()
        best_score = float(cur_score)

        acc = 0
        tried = 0
        trace_best: List[float] = []

        it = range(n_steps)
        if progress and _HAVE_TQDM:
            it = tqdm(it, desc="MCMC", leave=False)

        for t in it:
            prop, log_q_ratio = self.propose(cur, fixed_length=fixed_length)
            prop_score = self.logposterior(prop)

            tried += 1
            if np.isfinite(prop_score) and np.isfinite(cur_score):
                log_alpha = (prop_score - cur_score) / float(max(temperature, 1e-12)) + float(log_q_ratio)
                if math.log(self.rng.random()) < min(0.0, log_alpha):
                    cur = prop
                    cur_score = prop_score
                    acc += 1

            if float(cur_score) > best_score:
                best = cur.copy()
                best_score = float(cur_score)

            if t >= burn_in and (t - burn_in) % max(thin, 1) == 0:
                trace_best.append(best_score)

        return MCMCResult(
            best_master=best,
            best_score=best_score,
            trace_best_scores=trace_best,
            accept_rate=(acc / tried) if tried else 0.0,
        )


# -----------------------------
# Grid search wrappers
# -----------------------------


@dataclass
class GridSearchResult:
    best_master: np.ndarray
    best_params: IndelParams
    best_score: float
    all_results: List[Dict[str, Any]]


def grid_search_master(
    sequences: Sequence[TokenSeq],
    alphabet: Optional[Alphabet] = None,
    bg_model: Optional[BackgroundModel] = None,
    lengths: Optional[Sequence[int]] = None,
    p_ins_grid: Sequence[float] = (0.05, 0.1, 0.2),
    p_del_grid: Sequence[float] = (0.05, 0.1, 0.2),
    eps_sub: float = 0.01,
    n_steps: int = 3000,
    seed: int = 0,
    progress: bool = True,
) -> GridSearchResult:
    """Simple robust (but not fast) grid search over (L, p_ins, p_del).

    For each candidate, runs MCMC over the master sequence at fixed length L (substitution moves only).

    If lengths is None, uses a default candidate set based on observed lengths.
    """
    if alphabet is None:
        alphabet = Alphabet.from_sequences(sequences)
    if bg_model is None:
        bg_model = BackgroundModel.fit(sequences, alphabet=alphabet)

    enc_seqs = [alphabet.encode(s) for s in sequences]
    lens = [int(s.size) for s in enc_seqs]
    if lengths is None:
        mn, mx = int(min(lens)), int(max(lens))
        # Reasonable default: a few candidates around the median and below.
        med = int(np.median(lens))
        cand = sorted(set([max(1, med), max(1, med - mn // 4), max(1, med + mn // 4), max(1, mn // 2), mx]))
        lengths = cand

    all_res: List[Dict[str, Any]] = []
    best_score = -math.inf
    best_master = None
    best_params = None

    outer = [(L, pi, pd) for L in lengths for pi in p_ins_grid for pd in p_del_grid]

    it = outer
    if progress and _HAVE_TQDM:
        it = tqdm(outer, desc="Grid search", leave=False)

    for (L, p_ins, p_del) in it:
        params = IndelParams(p_ins=float(p_ins), p_del=float(p_del), bg_probs=bg_model.probs, eps_sub=float(eps_sub))
        est = MasterSequenceEstimator(alphabet=alphabet, sequences=sequences, params=params, seed=seed)

        init = est.init_random(length=int(L))
        res = est.run_mcmc(
            init_master=init,
            n_steps=int(n_steps),
            burn_in=max(100, int(n_steps // 10)),
            thin=max(5, int(n_steps // 100)),
            fixed_length=True,
            temperature=0.7,  # mild annealing
            progress=False,
        )
        all_res.append(
            {
                'L': int(L),
                'p_ins': float(p_ins),
                'p_del': float(p_del),
                'score': float(res.best_score),
                'accept_rate': float(res.accept_rate),
            }
        )
        if float(res.best_score) > best_score:
            best_score = float(res.best_score)
            best_master = res.best_master.copy()
            best_params = params

    assert best_master is not None and best_params is not None
    return GridSearchResult(
        best_master=best_master,
        best_params=best_params,
        best_score=float(best_score),
        all_results=all_res,
    )


# -----------------------------
# Simulation + evaluation utils
# -----------------------------


def simulate_observation(
    master: np.ndarray,
    params: Union[IndelParams, IndelModelParams],
    rng: np.random.Generator,
) -> np.ndarray:
    """Simulate one observed sequence from a master under the model."""
    master = np.asarray(master, dtype=np.int32)
    A = int(params.bg_probs.size)
    bg = np.asarray(params.bg_probs, dtype=np.float64)
    bg = bg / bg.sum()

    obs: List[int] = []

    def sample_bg() -> int:
        return int(rng.choice(A, p=bg))

    for sym in master.tolist():
        # inserts before this master symbol
        while rng.random() < params.p_ins:
            obs.append(sample_bg())

        # delete or emit
        if rng.random() < params.p_del:
            continue

        if params.eps_sub > 0.0 and rng.random() < params.eps_sub:
            obs.append(sample_bg())
        else:
            obs.append(int(sym))

    # tail inserts
    while rng.random() < params.p_ins:
        obs.append(sample_bg())

    return np.asarray(obs, dtype=np.int32)


def lcs_length(a: Sequence[int], b: Sequence[int]) -> int:
    """Length of longest common subsequence (O(len(a)*len(b)))."""
    n, m = len(a), len(b)
    if n == 0 or m == 0:
        return 0
    # Use two-row DP for memory.
    prev = np.zeros(m + 1, dtype=np.int32)
    cur = np.zeros(m + 1, dtype=np.int32)
    for i in range(1, n + 1):
        ai = a[i - 1]
        for j in range(1, m + 1):
            if ai == b[j - 1]:
                cur[j] = prev[j - 1] + 1
            else:
                cur[j] = cur[j - 1] if cur[j - 1] >= prev[j] else prev[j]
        prev, cur = cur, prev
    return int(prev[m])


def edit_distance(a: Sequence[int], b: Sequence[int]) -> int:
    """Levenshtein edit distance (insert/delete/substitute), O(n*m) time, O(m) memory."""
    n, m = len(a), len(b)
    if n == 0:
        return m
    if m == 0:
        return n
    prev = np.arange(m + 1, dtype=np.int32)
    cur = np.empty(m + 1, dtype=np.int32)
    for i in range(1, n + 1):
        cur[0] = i
        ai = a[i - 1]
        for j in range(1, m + 1):
            cost = 0 if ai == b[j - 1] else 1
            cur[j] = min(
                prev[j] + 1,        # delete
                cur[j - 1] + 1,     # insert
                prev[j - 1] + cost, # substitute
            )
        prev, cur = cur, prev
    return int(prev[m])


def decode_tokens(alphabet: Alphabet, seq: np.ndarray) -> List[str]:
    return alphabet.decode(seq)




def simulate_dataset(
    master_tokens: TokenSeq,
    n_obs: int,
    params: IndelModelParams,
    rng: Optional[np.random.Generator] = None,
) -> List[List[str]]:
    """Simulate a list of observed token sequences.

    Returns a list of token lists (not encoded ints), suitable for BackgroundModel.fit
    and MasterSequenceEstimator.
    """
    if rng is None:
        rng = np.random.default_rng(0)
    master_int = params.alphabet.encode(master_tokens)
    core = params.to_core()
    out: List[List[str]] = []
    for _ in range(int(n_obs)):
        obs_int = simulate_observation(master_int, core, rng)
        out.append(params.alphabet.decode(obs_int))
    return out



# -----------------------------
# Plug-in workflow: joint inference of master + parameters
# -----------------------------

@dataclass
class WorkflowResult:
    """Result of :func:`infer_master_workflow`."""

    master_tokens: List[str]
    params: IndelParams
    score: float
    diagnostics: Dict[str, Any]


def _choose_init_master_from_data(obs: List[np.ndarray], target_len: int, rng: np.random.Generator) -> np.ndarray:
    """Pick an observed sequence close to target_len; fall back to random."""
    if not obs:
        return np.zeros(0, dtype=np.int32)
    lens = np.array([int(o.size) for o in obs], dtype=np.int32)
    # prefer sequences not longer than target_len (helps avoid long masters)
    candidates = np.where(lens <= int(target_len))[0]
    if candidates.size == 0:
        idx = int(np.argmin(np.abs(lens - int(target_len))))
        return np.array(obs[idx], copy=True)
    # pick among closest lengths (ties broken randomly)
    cand_lens = lens[candidates]
    best = np.min(np.abs(cand_lens - int(target_len)))
    close = candidates[np.where(np.abs(cand_lens - int(target_len)) == best)[0]]
    idx = int(rng.choice(close))
    return np.array(obs[idx], copy=True)


def _estimate_p_ins_from_lengths(mean_len: float, L_master: int, p_del: float) -> float:
    """Heuristic p_ins init from mean observed length.

    Using E[obs_len] \approx (1-p_del)*L + (L+1)*p_ins/(1-p_ins).
    Solve for p_ins based on a guessed p_del.
    """
    L = max(1, int(L_master))
    base = (1.0 - float(p_del)) * float(L)
    ins_mean = max(0.0, float(mean_len) - base)
    # ins_mean = (L+1)*p/(1-p)  =>  p = ins_mean / (ins_mean + L+1)
    p = ins_mean / (ins_mean + float(L + 1)) if (ins_mean + float(L + 1)) > 0 else 0.0
    return float(np.clip(p, 1e-4, 0.8))


def _estimate_eps_sub_grid(
    emitted_pairs: List[Tuple[int, int]],
    bg_probs: np.ndarray,
    eps_max: float = 0.30,
    n_grid: int = 201,
) -> float:
    """1D grid MLE for eps_sub using aligned emissions.

    For each emitted pair (m, o):
        P(o|m) = (1-eps)*1_{o=m} + eps*bg(o)
    """
    if not emitted_pairs:
        return 0.0
    bg = np.asarray(bg_probs, dtype=np.float64)
    bg = bg / bg.sum()

    # Precompute bg(o) and equality flags.
    os = np.array([o for (_, o) in emitted_pairs], dtype=np.int32)
    ms = np.array([m for (m, _) in emitted_pairs], dtype=np.int32)
    eq = (os == ms)
    bg_o = bg[os]

    # Evaluate log-likelihood across grid.
    grid = np.linspace(0.0, float(eps_max), int(n_grid))
    ll = np.empty(grid.size, dtype=np.float64)
    for i, eps in enumerate(grid):
        if eps <= 0.0:
            # only possible if all are equal
            ll[i] = 0.0 if bool(eq.all()) else -np.inf
            continue
        # For eq positions: log((1-eps) + eps*bg(o)); else: log(eps*bg(o))
        ll_eq = np.log((1.0 - eps) + eps * bg_o[eq]) if bool(eq.any()) else 0.0
        ll_neq = np.log(eps * bg_o[~eq]) if bool((~eq).any()) else 0.0
        ll[i] = (ll_eq.sum() if isinstance(ll_eq, np.ndarray) else float(ll_eq)) + (
            ll_neq.sum() if isinstance(ll_neq, np.ndarray) else float(ll_neq)
        )

    best = int(np.nanargmax(ll))
    return float(grid[best])


def _em_fixed_length(
    obs: List[np.ndarray],
    master: np.ndarray,
    params: IndelParams,
    n_iters: int = 3,
    estimate_bg_from_inserts: bool = True,
    estimate_eps_sub: bool = True,
    bg_pseudocount: float = 1e-2,
    eps_max: float = 0.30,
    progress: bool = True,
    # If provided, these parameters are held fixed during the EM loop.
    fixed_p_ins: Optional[float] = None,
    fixed_p_del: Optional[float] = None,
    fixed_eps_sub: Optional[float] = None,
    fixed_bg_probs: Optional[np.ndarray] = None,
) -> Tuple[np.ndarray, IndelParams, Dict[str, Any]]:
    """EM-like loop (Viterbi E-step, closed-form M-step) at a fixed master length.

    This is designed for your regime: many short sequences (length ~ 10-20).
    """
    rng = np.random.default_rng(0)
    master = np.asarray(master, dtype=np.int32).copy()
    L = int(master.size)
    A = int(params.bg_probs.size)

    hist: Dict[str, Any] = {'iters': []}

    for it in range(int(n_iters)):
        lik = IndelLikelihood(params)

        # Sufficient statistics
        ins_total = 0
        del_total = 0
        match_total = 0

        # For master symbol update
        sym_counts = np.zeros((L, A), dtype=np.int64)

        # For background update (from inferred insertions)
        ins_bg_counts = np.zeros(A, dtype=np.int64)

        # For eps_sub update
        emitted_pairs: List[Tuple[int, int]] = []

        iterator = range(len(obs))
        if progress and _HAVE_TQDM:
            iterator = tqdm(iterator, desc=f"EM iter {it+1}/{n_iters}", leave=False)

        for s_idx in iterator:
            o = obs[s_idx]
            _, path = lik.viterbi_alignment(master, o)

            for step, mi, oj in path:
                if step == 'I':
                    j = int(oj)  # type: ignore[arg-type]
                    ins_total += 1
                    if 0 <= j < int(o.size):
                        ins_bg_counts[int(o[j])] += 1
                elif step == 'D':
                    del_total += 1
                else:  # 'M'
                    i = int(mi)  # type: ignore[arg-type]
                    j = int(oj)  # type: ignore[arg-type]
                    match_total += 1
                    if 0 <= i < L and 0 <= j < int(o.size):
                        sym = int(o[j])
                        sym_counts[i, sym] += 1
                        emitted_pairs.append((int(master[i]), sym))

        N = max(1, int(len(obs)))

        # --- M-step: update master symbols by per-position majority vote ---
        new_master = master.copy()
        for i in range(L):
            if sym_counts[i].sum() > 0:
                new_master[i] = int(np.argmax(sym_counts[i]))
            else:
                # If a position is never emitted, keep it (or randomize slightly)
                if rng.random() < 0.05:
                    new_master[i] = int(rng.integers(0, A))

        master = new_master

        # --- M-step: update parameters ---
        # p_del MLE: del / (del + match) with mild smoothing
        if fixed_p_del is not None:
            p_del_hat = float(fixed_p_del)
        else:
            denom_dm = float(del_total + match_total)
            if denom_dm <= 0:
                p_del_hat = params.p_del
            else:
                p_del_hat = float((del_total + 0.5) / (denom_dm + 1.0))

        # p_ins MLE under geometric runs: ins / (ins + runs), where runs = N*(L+1)
        if fixed_p_ins is not None:
            p_ins_hat = float(fixed_p_ins)
        else:
            runs = float(N * (L + 1))
            p_ins_hat = float((ins_total + 0.5) / (ins_total + runs + 1.0))

        # Background update: use inferred insertions if requested; otherwise keep.
        if fixed_bg_probs is not None:
            bg_probs = np.asarray(fixed_bg_probs, dtype=np.float64)
        else:
            bg_probs = np.asarray(params.bg_probs, dtype=np.float64)
            if estimate_bg_from_inserts:
                counts = np.full(A, float(bg_pseudocount), dtype=np.float64) + ins_bg_counts.astype(np.float64)
                bg_probs = counts / counts.sum()

        # eps_sub update from emitted pairs (optional)
        if fixed_eps_sub is not None:
            eps_hat = float(fixed_eps_sub)
        else:
            eps_hat = float(params.eps_sub)
            if estimate_eps_sub:
                eps_hat = _estimate_eps_sub_grid(emitted_pairs, bg_probs=bg_probs, eps_max=float(eps_max))

        params = IndelParams(
            p_ins=float(np.clip(p_ins_hat, 1e-4, 0.95)),
            p_del=float(np.clip(p_del_hat, 1e-4, 0.95)),
            bg_probs=np.asarray(bg_probs, dtype=np.float64),
            eps_sub=float(np.clip(eps_hat, 0.0, 0.95)),
        )

        # Track (forward) log-likelihood for monitoring
        ll = 0.0
        lik2 = IndelLikelihood(params)
        for o in obs:
            v = lik2.forward_loglik(master, o)
            if not np.isfinite(v):
                ll = -math.inf
                break
            ll += float(v)

        hist['iters'].append(
            {
                'iter': int(it),
                'p_ins': float(params.p_ins),
                'p_del': float(params.p_del),
                'eps_sub': float(params.eps_sub),
                'loglik': float(ll),
            }
        )

    return master, params, hist


def infer_master_workflow(
    sequences: Sequence[TokenSeq],
    *,
    alphabet: Optional[Alphabet] = None,
    # If you supply any of these, the default behavior is to treat them as FIXED (not estimated).
    bg_probs: Optional[np.ndarray] = None,
    p_ins: Optional[float] = None,
    p_del: Optional[float] = None,
    eps_sub: Optional[float] = None,
    fix_provided_params: bool = True,
    # Length control: in your use-case, the default is a *hard cap* at ~12.
    target_master_len: int = 12,
    max_master_len: int = 12,
    lengths: Optional[Sequence[int]] = None,
    # Parameter estimation
    bg_pseudocount: float = 1e-2,
    estimate_bg_from_inserts: bool = True,
    estimate_eps_sub: bool = True,
    eps_max: float = 0.30,
    # Search / robustness
    n_restarts: int = 2,
    em_iters: int = 3,
    grid_search_params: bool = False,
    p_ins_grid: Sequence[float] = (0.02, 0.05, 0.10, 0.20),
    p_del_grid: Sequence[float] = (0.05, 0.10, 0.20, 0.35),
    # Optional MCMC polishing (off by default for large-N regimes)
    do_mcmc_refine: Optional[bool] = None,
    mcmc_steps_refine: int = 800,
    mcmc_temperature: float = 0.7,
    # Scaling controls
    search_subset_size: int = 2000,
    seed: int = 0,
    progress: bool = True,
) -> WorkflowResult:
    """One-call workflow: infer master sequence and (p_ins, p_del, bg, eps_sub).

    Designed defaults for your stated regime:
      - N in [200, 10_000]
      - alphabet size: a few dozen
      - observed lengths: ~ a dozen

    Important default behavior:
      - The inferred master length is capped by ``max_master_len`` (default 12).
        This prevents the workflow from returning long masters even if a naive model
        would assign them high likelihood.

    Inputs
    ------
    sequences:
        A list of observed sequences, each either a string or a list of tokens.

    Returns
    -------
    WorkflowResult with fields:
      - master_tokens: list[str]
      - params: IndelParams
      - score: forward log-likelihood of the final model on *all* sequences
      - diagnostics: details (history, candidate scores, subset sizing)
    """

    if alphabet is None:
        alphabet = Alphabet.from_sequences(sequences)

    # Encode all sequences.
    obs_all = [alphabet.encode(s) for s in sequences]
    N = int(len(obs_all))
    rng = np.random.default_rng(int(seed))

    # Fit an initial background model from all observations (unless bg_probs is provided).
    if bg_probs is None:
        bg_model = BackgroundModel.fit(sequences, alphabet=alphabet, pseudocount=float(bg_pseudocount))
        bg_init = np.asarray(bg_model.probs, dtype=np.float64)
    else:
        bg_init = np.asarray(bg_probs, dtype=np.float64)
        if bg_init.ndim != 1 or bg_init.size != alphabet.size:
            raise ValueError('bg_probs must be a 1D array of length alphabet.size')
        bg_init = bg_init / bg_init.sum()
        bg_model = BackgroundModel(alphabet=alphabet, probs=bg_init)

    # Choose subset for candidate search (keeps runtime stable for large N).
    if N > int(search_subset_size):
        idx = rng.choice(N, size=int(search_subset_size), replace=False)
        obs_search = [obs_all[int(i)] for i in idx]
        sequences_search = [sequences[int(i)] for i in idx]
    else:
        idx = np.arange(N, dtype=np.int32)
        obs_search = obs_all
        sequences_search = sequences

    lens = np.array([int(o.size) for o in obs_all], dtype=np.int32)

    # Candidate master lengths: by default, a small range ending at max_master_len.
    if lengths is None:
        Lmax = int(max_master_len)
        Lmin = max(1, Lmax - 5)
        lengths = list(range(Lmin, Lmax + 1))
    else:
        lengths = [int(L) for L in lengths if 1 <= int(L) <= int(max_master_len)]
        if not lengths:
            raise ValueError("lengths is empty after applying max_master_len cap")

    # Default for MCMC polishing: only do it automatically for smaller N.
    if do_mcmc_refine is None:
        do_mcmc_refine = (N <= 1500)

    diagnostics: Dict[str, Any] = {
        'N': int(N),
        'fixed': {
            'bg_probs': bool(bg_probs is not None and fix_provided_params),
            'p_ins': bool(p_ins is not None and fix_provided_params),
            'p_del': bool(p_del is not None and fix_provided_params),
            'eps_sub': bool(eps_sub is not None and fix_provided_params),
        },
        'search_subset_size_used': int(len(obs_search)),
        'length_candidates': list(lengths),
        'target_master_len': int(target_master_len),
        'max_master_len': int(max_master_len),
        'candidates': [],
    }

    best = {
        'score': -math.inf,
        'master': None,
        'params': None,
        'hist': None,
        'L': None,
    }

    # Optionally do a small parameter grid search (rarely needed with EM, but included).
    if grid_search_params:
        p_ins_list = list(p_ins_grid)
        p_del_list = list(p_del_grid)
    else:
        p_ins_list = [None]
        p_del_list = [None]

    # Outer search loop over lengths (and optionally p-ins/p-del grid)
    outer = [(L, pi, pd) for L in lengths for pi in p_ins_list for pd in p_del_list]
    it_outer = outer
    if progress and _HAVE_TQDM:
        it_outer = tqdm(outer, desc="Workflow search", leave=False)

    for (L, pi, pd) in it_outer:
        L = int(L)

        # Heuristic initial params
        mean_len = float(lens.mean())
        p_del0 = float(p_del) if p_del is not None else (float(pd) if pd is not None else 0.20)
        p_ins0 = float(p_ins) if p_ins is not None else (float(pi) if pi is not None else _estimate_p_ins_from_lengths(mean_len, L, p_del0))
        eps0 = float(eps_sub) if eps_sub is not None else 0.02

        params0 = IndelParams(
            p_ins=float(np.clip(p_ins0, 1e-4, 0.9)),
            p_del=float(np.clip(p_del0, 1e-4, 0.9)),
            bg_probs=np.asarray(bg_model.probs, dtype=np.float64),
            eps_sub=float(eps0),
        )

        # Multiple restarts: different master initializations, take best
        local_best = {'score': -math.inf, 'master': None, 'params': None, 'hist': None}

        for r in range(int(max(1, n_restarts))):
            # init master either from data (closest) or random
            if r == 0:
                init_m = _choose_init_master_from_data(obs_search, target_len=min(L, target_master_len), rng=rng)
            else:
                init_m = rng.integers(0, alphabet.size, size=L, dtype=np.int32)

            # Ensure correct length
            if int(init_m.size) != L:
                init_m = rng.integers(0, alphabet.size, size=L, dtype=np.int32)

            m_em, p_em, hist = _em_fixed_length(
                obs=obs_search,
                master=init_m,
                params=params0,
                n_iters=int(em_iters),
                estimate_bg_from_inserts=bool(estimate_bg_from_inserts),
                estimate_eps_sub=bool(estimate_eps_sub),
                bg_pseudocount=float(bg_pseudocount),
                eps_max=float(eps_max),
                progress=False,
                fixed_p_ins=float(p_ins) if (p_ins is not None and fix_provided_params) else None,
                fixed_p_del=float(p_del) if (p_del is not None and fix_provided_params) else None,
                fixed_eps_sub=float(eps_sub) if (eps_sub is not None and fix_provided_params) else None,
                fixed_bg_probs=bg_init if (bg_probs is not None and fix_provided_params) else None,
            )

            # Score on search subset (forward likelihood, not Viterbi)
            lik = IndelLikelihood(p_em)
            ll = 0.0
            for o in obs_search:
                v = lik.forward_loglik(m_em, o)
                if not np.isfinite(v):
                    ll = -math.inf
                    break
                ll += float(v)

            if float(ll) > float(local_best['score']):
                local_best = {'score': float(ll), 'master': m_em.copy(), 'params': p_em, 'hist': hist}

        diagnostics['candidates'].append(
            {
                'L': int(L),
                'p_ins_init': float(p_ins0),
                'p_del_init': float(p_del0),
                'search_subset_loglik': float(local_best['score']),
            }
        )

        if float(local_best['score']) > float(best['score']):
            best = {
                'score': float(local_best['score']),
                'master': local_best['master'],
                'params': local_best['params'],
                'hist': local_best['hist'],
                'L': int(L),
            }

    assert best['master'] is not None and best['params'] is not None
    master_best = np.asarray(best['master'], dtype=np.int32)
    params_best: IndelParams = best['params']

    # Optional MCMC polish (fixed-length by default to respect max_master_len)
    if bool(do_mcmc_refine):
        est = MasterSequenceEstimator(
            alphabet=alphabet,
            sequences=sequences_search,
            params=params_best,
            seed=int(seed),
        )
        res = est.run_mcmc(
            init_master=master_best,
            n_steps=int(mcmc_steps_refine),
            burn_in=max(100, int(mcmc_steps_refine // 5)),
            thin=max(5, int(mcmc_steps_refine // 100)),
            fixed_length=True,
            temperature=float(mcmc_temperature),
            progress=False,
        )
        master_best = res.best_master.copy()

    # Final parameter refresh on full data (still fixed-length, capped)
    master_final, params_final, hist_full = _em_fixed_length(
        obs=obs_all,
        master=master_best,
        params=params_best,
        n_iters=max(1, int(em_iters)),
        estimate_bg_from_inserts=bool(estimate_bg_from_inserts),
        estimate_eps_sub=bool(estimate_eps_sub),
        bg_pseudocount=float(bg_pseudocount),
        eps_max=float(eps_max),
        progress=False,
        fixed_p_ins=float(p_ins) if (p_ins is not None and fix_provided_params) else None,
        fixed_p_del=float(p_del) if (p_del is not None and fix_provided_params) else None,
        fixed_eps_sub=float(eps_sub) if (eps_sub is not None and fix_provided_params) else None,
        fixed_bg_probs=bg_init if (bg_probs is not None and fix_provided_params) else None,
    )

    # Full-data forward log-likelihood score
    lik_full = IndelLikelihood(params_final)
    full_ll = 0.0
    for o in obs_all:
        v = lik_full.forward_loglik(master_final, o)
        if not np.isfinite(v):
            full_ll = -math.inf
            break
        full_ll += float(v)

    diagnostics['best_length'] = int(master_final.size)
    diagnostics['best_search_subset_loglik'] = float(best['score'])
    diagnostics['em_history_search'] = best['hist']
    diagnostics['em_history_full'] = hist_full
    diagnostics['do_mcmc_refine'] = bool(do_mcmc_refine)

    return WorkflowResult(
        master_tokens=alphabet.decode(master_final),
        params=params_final,
        score=float(full_ll),
        diagnostics=diagnostics,
    )
if __name__ == "__main__":
    # Tiny smoke test
    rng = np.random.default_rng(0)
    seqs = ["ABRACADABRA", "ABRA", "CADABRA"]
    alphabet = Alphabet.from_sequences(seqs)
    bg = BackgroundModel.fit(seqs, alphabet)
    params = IndelParams(p_ins=0.1, p_del=0.2, bg_probs=bg.probs, eps_sub=0.01)
    est = MasterSequenceEstimator(alphabet, seqs, params, seed=0)
    init = est.init_from_shortest()
    res = est.run_mcmc(init_master=init, n_steps=200, burn_in=50, thin=5, fixed_length=False, progress=False)
    print("Accept rate:", res.accept_rate)
    print("Best master:", "".join(decode_tokens(alphabet, res.best_master)))
